/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.gameovermenu;

import controllers.IAmTheAntivirus;
import java.awt.Color;
import java.awt.Font;
import menu.AbstractMenuViewController;
import utilities.FontUtilities;

/**
 *
 * @author admin
 */
public class GameOverViewController extends AbstractMenuViewController {

    private Color backgroundColor = Color.BLUE;
    private Color foregroundColor = Color.WHITE;
    private Font minecraftFont = FontUtilities.registerFont("src/resources/fonts/Minecraft.ttf");
    
    public GameOverViewController() {
        initComponents();
       
        setBackground(backgroundColor);
        retryButton.setBackground(backgroundColor);
        retryButton.setForeground(foregroundColor);

        
        backToMainMenuButton.setBackground(backgroundColor);
        backToMainMenuButton.setForeground(foregroundColor);
        
        gameOverTitle.setForeground(foregroundColor);
        gameOverTitle.setBackground(backgroundColor);
        gameOverTitle.setFont(new Font("Minecraft", Font.BOLD, 40));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retryButton = new menu.RetroButton();
        backToMainMenuButton = new menu.RetroButton();
        gameOverTitle = new javax.swing.JLabel();

        retryButton.setText("retry");
        retryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryButtonActionPerformed(evt);
            }
        });

        backToMainMenuButton.setText("back to main menu");
        backToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenuButtonActionPerformed(evt);
            }
        });

        gameOverTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        gameOverTitle.setText("GAME OVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(gameOverTitle)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(gameOverTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(retryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void retryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryButtonActionPerformed
       IAmTheAntivirus gameApplication = IAmTheAntivirus.getGameInstance();
       gameApplication.startGame();

    }//GEN-LAST:event_retryButtonActionPerformed

    private void backToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenuButtonActionPerformed
       IAmTheAntivirus gameApplication = IAmTheAntivirus.getGameInstance();
       gameApplication.displayMainMenu();
    }//GEN-LAST:event_backToMainMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private menu.RetroButton backToMainMenuButton;
    private javax.swing.JLabel gameOverTitle;
    private menu.RetroButton retryButton;
    // End of variables declaration//GEN-END:variables
}
