/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.shopmenu;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author gabri
 */
public class ShopItemView extends javax.swing.JPanel {

    /**
     * Creates new form MyComponent
     */
    private int margin;
    public ShopItemView() {
        initComponents();
        
    }

    public void setCostLabel(String value) {
        this.costLabel.setText(value);
    }


    public void setDescriptionLabel(String value) {
        this.descriptionLabel.setText(value);
    }


    public void setNameLabel(String value) {
        this.nameLabel.setText(value);
    }


    public void setNextValueLabel(String value) {
        this.nextValueLabel.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        costLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        nextValueLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        progressBar = new menu.shopmenu.ProgressBar();
        plusButton = new menu.RetroButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 300));
        setLayout(null);

        costLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        costLabel.setForeground(new java.awt.Color(255, 255, 255));
        costLabel.setText("500");
        add(costLabel);
        costLabel.setBounds(500, 40, 48, 50);

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("Increase your max health to:");
        add(descriptionLabel);
        descriptionLabel.setBounds(33, 115, 178, 64);

        nextValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nextValueLabel.setForeground(java.awt.Color.green);
        nextValueLabel.setText("50");
        add(nextValueLabel);
        nextValueLabel.setBounds(218, 139, 48, 17);

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Max Health:");
        nameLabel.setPreferredSize(new java.awt.Dimension(68, 50));
        add(nameLabel);
        nameLabel.setBounds(33, 44, 135, 33);

        javax.swing.GroupLayout progressBarLayout = new javax.swing.GroupLayout(progressBar);
        progressBar.setLayout(progressBarLayout);
        progressBarLayout.setHorizontalGroup(
            progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        progressBarLayout.setVerticalGroup(
            progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        add(progressBar);
        progressBar.setBounds(180, 40, 241, 47);

        plusButton.setText("+");
        plusButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                plusButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                plusButtonFocusLost(evt);
            }
        });
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        add(plusButton);
        plusButton.setBounds(430, 40, 50, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plusButtonFocusGained
        plusButton.toggleColors();
    }//GEN-LAST:event_plusButtonFocusGained

    private void plusButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plusButtonFocusLost
        plusButton.toggleColors();
    }//GEN-LAST:event_plusButtonFocusLost

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        progressBar.increaseProgression();
    }//GEN-LAST:event_plusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nextValueLabel;
    private menu.RetroButton plusButton;
    private menu.shopmenu.ProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
