/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.shopmenu;

import java.awt.Component;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author gabri
 */
public class ShopMenuViewController extends javax.swing.JPanel {
    
    private Map<String,ShopItemView> items = new HashMap<>();
    
    /**
     * Creates new form ShopMenuViewController
     */
    public ShopMenuViewController() {
        initComponents();
        
        
        
    }
    
    private void initItems(){
        
        ShopItemView health = new ShopItemView();
        health.setNameLabel("Health");
        health.setCostValue(50);
        health.setDescriptionLabel("Increase the maximum health of your base to:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopItemView1 = new menu.shopmenu.ShopItemView();

        setBackground(new java.awt.Color(204, 204, 204));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(null);
        add(shopItemView1);
        shopItemView1.setBounds(50, 41, 600, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        Component parent = this.getParent();
        int width = (int) (parent.getWidth() * 0.7);
        int height = (int)(parent.getHeight()*0.9);
        int x = (parent.getWidth() - width)/2;
        int y = (parent.getHeight() - height)/2;
        this.setBounds(x, y, width, height);
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private menu.shopmenu.ShopItemView shopItemView1;
    // End of variables declaration//GEN-END:variables
}
